FROM freqtradeorg/freqtrade:develop

# Install dependencies
COPY requirements-postgres.txt /freqtrade/
RUN pip install numpy --no-cache-dir \
  && pip install -r requirements-postgres.txt --no-cache-dir

# Empty the ENTRYPOINT to allow all commands
ENTRYPOINT ["freqtrade"]
