---
version: '3'
services:
  freqtrade_postgres:
    build:
      context: .
      dockerfile: "./Dockerfile.postgres"
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./config.json:/freqtrade/config.json"
      - "./freqtrade:/freqtrade/freqtrade"
    depends_on:
      - db

  pytest:
    build:
      context: .
      dockerfile: "./Dockerfile.develop"
    volumes:
      - ".:/freqtrade"
    command:
      ["./scripts/pytest.sh"]

  db:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES: postgres
      POSTGRES_DB: postgres

  toolkit:
    image: toolkit
